version: 0.2

phases:
  install:
    # runtime-versions:
    #   java: corretto11
    - cd country-api && pip install -r requirements.txt
    - pip install pycodestyle

  pre_build:
    # commands:
    #   - echo Nothing to do in the pre_build phase...
  build:
    commands:
      # - echo Build started on `date`
      # - mvn install
      # pep 8 style guide lines
      - pycodestyle -v src/*.py 
      - echo "pycodestyle found not issues"
      # python -m pytest

  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - src/*
  
  discard-paths: yes
  base-directory: country-api
  name: country-api-$(date +%Y-%m-%d-%H-%M-%S).zip